//------------------------------------------------------------------------------
// <auto-generated>
//     This xml documentation was generated by CXCommenter: 1.0.1.0.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright file="GameRepository.cs" company="Arkayn Game Designs">
//     Copyright (c) Arkayn Game Designs. All rights reserved.
// </copyright>
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using ArkaynDAL;
using ArkaynDAL.Core;
using ArkaynDAL.Interfaces;
using EACore_Data.Models;

/// <summary>
///       Namespace Name - EA_Aide.DataAccess.
/// </summary>
namespace EA_Aide.DataAccess
{
    public class GameRepository : RepositoryBase
    {

        /// <summary>
        ///  Function Name :  GameRepository.
        /// </summary>
        /// <param name="conn">This conn's Datatype is : ArkaynDAL.Interfaces.IArkaynConnection.</param>
        /// <returns>void.</returns>
        public GameRepository(IArkaynConnection conn) : base(conn)
        {
        }


        /// <summary>
        ///  Function Name :  GetAllGamesAsync.
        /// </summary>
        /// <returns>System.Threading.Tasks.Task<System.Collections.Generic.List<EACore_Data.Models.Game>>.</returns>
        public async Task<List<Game>> GetAllGamesAsync()
        {
            var games = new List<Game>();

            using var reader = await _conn.ExecuteReaderAsync("SELECT * FROM Games");
            while (reader.Read())
            {
                games.Add(MapGame(reader));
            }

            return games;
        }


        /// <summary>
        ///  Function Name :  GetGameByIdAsync.
        /// </summary>
        /// <param name="gameId">This gameId's Datatype is : int.</param>
        /// <returns>System.Threading.Tasks.Task<EACore_Data.Models.Game>.</returns>
        public async Task<Game> GetGameByIdAsync(int gameId)
        {
            using var reader = await _conn.ExecuteReaderAsync(
                "SELECT * FROM Games WHERE GameID=@id",
                new ArkaynParameter("@id", gameId)
            );

            if (reader.Read())
                return MapGame(reader);

            return null;
        }


        /// <summary>
        ///  Function Name :  AddGameAsync.
        /// </summary>
        /// <param name="game">This game's Datatype is : EACore_Data.Models.Game.</param>
        /// <returns>System.Threading.Tasks.Task<int>.</returns>
        public async Task<int> AddGameAsync(Game game)
        {
            var sql = @"
                INSERT INTO Games (
                    GameName, GMName, Notes,
                    CreatedOn, LastUpdated,
                    CurrentDate, CurrentTime,
                    Password,
                    CreatedMajorVer, CreatedMinorVer, CreatedBuildVer,
                    LastUpdateMajor, LastUpdateMinor, LastUpdateBuild
                )
                VALUES (
                    @GameName, @GMName, @Notes,
                    @CreatedOn, @LastUpdated,
                    @CurrentDate, @CurrentTime,
                    @Password,
                    @CreatedMajorVer, @CreatedMinorVer, @CreatedBuildVer,
                    @LastUpdateMajor, @LastUpdateMinor, @LastUpdateBuild
                );
                SELECT last_insert_rowid();
            ";

            return await _conn.ExecuteScalarAsync<int>(
                sql,
                BuildParameters(game)
            );
        }


        /// <summary>
        ///  Function Name :  UpdateGameAsync.
        /// </summary>
        /// <param name="game">This game's Datatype is : EACore_Data.Models.Game.</param>
        /// <returns>System.Threading.Tasks.Task.</returns>
        public async Task UpdateGameAsync(Game game)
        {
            var sql = @"
                UPDATE Games SET
                    GameName=@GameName,
                    GMName=@GMName,
                    Notes=@Notes,
                    CreatedOn=@CreatedOn,
                    LastUpdated=@LastUpdated,
                    CurrentDate=@CurrentDate,
                    CurrentTime=@CurrentTime,
                    Password=@Password,
                    CreatedMajorVer=@CreatedMajorVer,
                    CreatedMinorVer=@CreatedMinorVer,
                    CreatedBuildVer=@CreatedBuildVer,
                    LastUpdateMajor=@LastUpdateMajor,
                    LastUpdateMinor=@LastUpdateMinor,
                    LastUpdateBuild=@LastUpdateBuild
                WHERE GameID=@GameID
            ";

            await _conn.ExecuteNonQueryAsync(sql, BuildParameters(game));
        }


        /// <summary>
        ///  Function Name :  DeleteGameAsync.
        /// </summary>
        /// <param name="gameId">This gameId's Datatype is : int.</param>
        /// <returns>System.Threading.Tasks.Task.</returns>
        public async Task DeleteGameAsync(int gameId)
        {
            await _conn.ExecuteNonQueryAsync(
                "DELETE FROM Games WHERE GameID=@id",
                new ArkaynParameter("@id", gameId)
            );
        }


        /// <summary>
        ///  Function Name :  BuildParameters.
        /// </summary>
        /// <param name="game">This game's Datatype is : EACore_Data.Models.Game.</param>
        /// <param name="includeId">This includeId's Datatype is : bool.</param>
        /// <returns>ArkaynDAL.Core.ArkaynParameter[].</returns>
        private ArkaynParameter[] BuildParameters(Game game, bool includeId = false)
        {
            var list = new List<ArkaynParameter>
    {
        new ArkaynParameter("@GameName", game.GameName),
        new ArkaynParameter("@GMName", game.GMName),
        new ArkaynParameter("@Notes", game.Notes),

        new ArkaynParameter("@CreatedOn", game.CreatedOn),
        new ArkaynParameter("@LastUpdated", game.LastUpdated),

        new ArkaynParameter("@CurrentDate", game.CurrentDate),
        new ArkaynParameter("@CurrentTime", game.CurrentTime),

        new ArkaynParameter("@Password", game.Password),

                new ArkaynParameter("@CreatedMajorVer", game.CreatedVersion.Major),
        new ArkaynParameter("@CreatedMinorVer", game.CreatedVersion.Minor),
        new ArkaynParameter("@CreatedBuildVer", game.CreatedVersion.Build),

                new ArkaynParameter("@LastUpdateMajor", game.LastUpdatedVersion?.Major),
        new ArkaynParameter("@LastUpdateMinor", game.LastUpdatedVersion?.Minor),
        new ArkaynParameter("@LastUpdateBuild", game.LastUpdatedVersion?.Build)
    };

            if (includeId)
                list.Add(new ArkaynParameter("@GameID", game.GameID));

            return list.ToArray();
        }


        /// <summary>
        ///  Function Name :  MapGame.
        /// </summary>
        /// <param name="reader">This reader's Datatype is : ArkaynDAL.Interfaces.IArkaynReader.</param>
        /// <returns>EACore_Data.Models.Game.</returns>
        private Game MapGame(IArkaynReader reader)
        {
            var game = new Game
            {
                GameID = reader.GetInt32("GameID"),

                GameName = reader.GetNullableString("GameName")!,
                GMName = reader.GetNullableString("GMName"),
                Notes = reader.GetNullableString("Notes"),

                CreatedOn = reader.GetDateTime("CreatedOn"),
                LastUpdated = reader.GetNullableDateTime("LastUpdated"),

                CurrentDate = reader.GetNullableDateTime("CurrentDate"),
                CurrentTime = reader.GetNullableTimeSpan("CurrentTime"),

                Password = reader.GetNullableString("Password"),

                CreatedVersion = new GameVersion
                {
                    Major = reader.GetInt32("CreatedMajorVer"),
                    Minor = reader.GetInt32("CreatedMinorVer"),
                    Build = reader.GetInt32("CreatedBuildVer")
                }
            };

            if (!reader.IsDBNull("LastUpdateMajor"))
            {
                game.LastUpdatedVersion = new GameVersion
                {
                    Major = reader.GetInt32("LastUpdateMajor"),
                    Minor = reader.GetInt32("LastUpdateMinor"),
                    Build = reader.GetInt32("LastUpdateBuild")
                };
            }

            return game;
        }

    }
}
