//------------------------------------------------------------------------------
// <auto-generated>
//     This xml documentation was generated by CXCommenter: 1.0.1.0.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright file="PlayerRepository.cs" company="Arkayn Game Designs">
//     Copyright (c) Arkayn Game Designs. All rights reserved.
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;
using ArkaynDAL;
using ArkaynDAL.Core;
using ArkaynDAL.Interfaces;
using EACore_Data.Models;

/// <summary>
///       Namespace Name - EA_Aide.DataAccess.
/// </summary>
namespace EA_Aide.DataAccess
{
    public class PlayerRepository : RepositoryBase

    {

        /// <summary>
        ///  Function Name :  PlayerRepository.
        /// </summary>
        /// <param name="_conn">This _conn's Datatype is : ArkaynDAL.Interfaces.IArkaynConnection.</param>
        /// <returns>void.</returns>
        public PlayerRepository(IArkaynConnection _conn) : base(_conn) { }


        /// <summary>
        ///  Function Name :  GetAllPlayersAsync.
        /// </summary>
        /// <returns>System.Threading.Tasks.Task<System.Collections.Generic.List<EACore_Data.Models.Player>>.</returns>
        public async Task<List<Player>> GetAllPlayersAsync()
        {
            var players = new List<Player>();

            using var reader = await _conn.ExecuteReaderAsync("SELECT * FROM Players");
            while (reader.Read())
            {
                players.Add(MapPlayer(reader));
            }

            return players;
        }


        /// <summary>
        ///  Function Name :  GetPlayerByIdAsync.
        /// </summary>
        /// <param name="playerID">This playerID's Datatype is : int.</param>
        /// <returns>System.Threading.Tasks.Task<EACore_Data.Models.Player>.</returns>
        public async Task<Player> GetPlayerByIdAsync(int playerID)
        {
            using var reader = await _conn.ExecuteReaderAsync(
                "SELECT * FROM Players WHERE PlayerID=@id",
                new ArkaynParameter("@id", playerID)
            );

            if (reader.Read())
                return MapPlayer(reader);

            return null;
        }

        /// <summary>
        ///  Function Name :  AddPlayerAsync.
        /// </summary>
        /// <param name="player">This player's Datatype is : EACore_Data.Models.Player.</param>
        /// <returns>System.Threading.Tasks.Task<int>.</returns>
        public async Task<int> AddPlayerAsync(Player player)
        {
            var sql = @"
                INSERT INTO Players (
                    PlayerName, UserName, Email, Notes, CreatedOn, LastUpdated
                )
                VALUES (
                    @PlayerName, @UserName, @Email, @Notes, @CreatedOn, @LastUpdated
                );
                SELECT last_insert_rowid();
            ";

            return await _conn.ExecuteScalarAsync<int>(
                sql,
                BuildParameters(player)
            );
        }


        /// <summary>
        ///  Function Name :  UpdatePlayerAsync.
        /// </summary>
        /// <param name="player">This player's Datatype is : EACore_Data.Models.Player.</param>
        /// <returns>System.Threading.Tasks.Task.</returns>
        public async Task UpdatePlayerAsync(Player player)
        {
            var sql = @"
                UPDATE Players SET
                    PlayerName = @PlayerName,
                    UserName = @UserName,
                    Email = @Email,
                    Notes = @Notes,
                    CreatedOn = @CreatedOn,
                    LastUpdated = @LastUpdated
                WHERE PlayerID=@PlayerID
            ";

            await _conn.ExecuteNonQueryAsync(sql, BuildParameters(player));
        }


        /// <summary>
        ///  Function Name :  DeletePlayerAsync.
        /// </summary>
        /// <param name="playerID">This playerID's Datatype is : int.</param>
        /// <returns>System.Threading.Tasks.Task.</returns>
        public async Task DeletePlayerAsync(int playerID)
        {
            await _conn.ExecuteNonQueryAsync(
                "DELETE FROM Players WHERE PlayerID=@id",
                new ArkaynParameter("@id", playerID)
            );
        }


        /// <summary>
        ///  Function Name :  BuildParameters.
        /// </summary>
        /// <param name="player">This player's Datatype is : EACore_Data.Models.Player.</param>
        /// <param name="includeId">This includeId's Datatype is : bool.</param>
        /// <returns>ArkaynDAL.Core.ArkaynParameter[].</returns>
        private ArkaynParameter[] BuildParameters(Player player, bool includeId = false)
        {
            var list = new List<ArkaynParameter>
    {
        new ArkaynParameter("@PlayerName", player.PlayerName),
        new ArkaynParameter("@UserName", player.UserName),
        new ArkaynParameter("@Email", player.Email),
        new ArkaynParameter("@Notes", player.Notes),
        new ArkaynParameter("@CreatedOn", player.CreatedOn),
        new ArkaynParameter("@LastUpdated", player.LastUpdated)
    };

            if (includeId)
                list.Add(new ArkaynParameter("@GameID", player.PlayerID));

            return list.ToArray();
        }


        /// <summary>
        ///  Function Name :  MapPlayer.
        /// </summary>
        /// <param name="reader">This reader's Datatype is : ArkaynDAL.Interfaces.IArkaynReader.</param>
        /// <returns>EACore_Data.Models.Player.</returns>
        private Player MapPlayer(IArkaynReader reader)
        {
            var player = new Player
            {
                PlayerID = reader.GetInt32("PlayerID"),

                PlayerName = reader.GetString("PlayerName")!,
                UserName = reader.GetNullableString("UserName"),
                Email = reader.GetNullableString("Email"),
                Notes = reader.GetNullableString("Notes"),

                CreatedOn = reader.GetDateTime("CreatedOn"),
                LastUpdated = reader.GetNullableDateTime("LastUpdated"),

            };


            return player;
        }
    }
}