//------------------------------------------------------------------------------
// <auto-generated>
//     This xml documentation was generated by CXCommenter: 1.0.1.0.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright file="RepositoryBase.cs" company="Arkayn Game Designs">
//     Copyright (c) Arkayn Game Designs. All rights reserved.
// </copyright>
using ArkaynDAL;
using ArkaynDAL.Interfaces;

/// <summary>
///       Namespace Name - EA_Aide.DataAccess.
/// </summary>
namespace EA_Aide.DataAccess
{
    public abstract class RepositoryBase
    {
        protected readonly IArkaynConnection _conn;


        /// <summary>
        ///  Function Name :  RepositoryBase.
        /// </summary>
        /// <param name="conn">This conn's Datatype is : ArkaynDAL.Interfaces.IArkaynConnection.</param>
        /// <returns>void.</returns>
        protected RepositoryBase(IArkaynConnection conn)
        {
            _conn = conn;
        }
    }
}
